### ISSUE TITLE
using private repos per student

### ISSUE THREAD

**Issue by dpastoor** [jennybc/2015-06-28_r-summit-talk#1]
Hi Jenny,

Fantastic material - glad I can use your material as a reference for 'how it should be done' when pitching my ideas! One question I had was how you set up the private repos for all the students? Did you have them all get github developer accounts and send you/the organization an invite? I am trying to figure out the 'best' way to manage students private repos from a cost perspective, especially for larger classes. 

I've considered just using bitbucket or self-hosting on gitlab, but I am just so comfortable with github and want the students to (hopefully) get exposed to its community.

**Comment by jennybc** [comment]
Hello @dpastoor ,

Thanks for the kinds words. Of course you can refer to this material!

In 2014/2015, I got private repos by requesting a free Gold Organization through GitHub Education. I highly recommend this route. This way you have lots of power over the repos and do lots of things programmatically. Just request in plenty of time before your course starts.

In 2013/2014, I asked each student to request their ~5 free private repos that GitHub gives to students. This is NOT recommended. It worked but is much more trouble.

I do plant to write down more specifics but here are rough notes:
http://stat545-ubc.github.io/bit004_stat545-use-of-github.html

This will be much nicer in 2015/2016 because GitHub has added alot of flexibility to Organizations and Teams.

HTH.

**Comment by dpastoor** [comment]
perfect - just the info I needed! Yes, I dredded how many emails and office hours it would take to get everyone set up with their own private repos.
